# **ESEG - Data Science II**

**Aula 1 - Trabalhando com numpy**

In [4]:
# importando o numpy
import numpy as np

Arrays - forma mais prática de trabalhar com lista de valores

In [5]:
# Array unidimensional
np.array([1,2,3])

array([1, 2, 3])

In [6]:
# Array bidimensional
np.array([[1,2,3],[4,5,6]])

array([[1, 2, 3],
       [4, 5, 6]])

In [9]:
# Array tridimensional
np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])

array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]]])

Podemos criar arrays específicos preenchidos por zeros ou uns:

In [10]:
one = np.ones([2,2])
one

array([[1., 1.],
       [1., 1.]])

In [18]:
zeros = np.zeros([2,2,2])
zeros

array([[[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]]])

Podemos acessar elementos dos arrays indicando a sua posição:

In [14]:
data = np.array([0,1,2,3,4,5,6,7,8,9])

Acessando o elemento na posição 2. Lembrando que o array inicia na posição 0:

In [19]:
data[2]

2

Acessando os elementos presentes em um intervalo do array:

In [20]:
data[2:5]

array([2, 3, 4])

Array com mais de uma dimensão. Acessando os elementos:

In [21]:
vet = np.array([[1,2,3],[4,5,6],[7,8,9]])
vet

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

Da mesma forma como o array unidimensional, a contagem de linha e coluna inicia no 0,0. Desta forma para buscar elementos no array bidimensional usamos:

**linha : coluna**

In [22]:
# segunda linha sem restrição de coluna
vet[1,:] 

array([4, 5, 6])

In [23]:
# terceira coluna de todas as linhas
vet[:,2]

array([3, 6, 9])

In [24]:
# elemento existente na posição 1,1
vet[1,1]

5

Considerando agora duas matriz de 2 por 2:

In [25]:
arr = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
arr

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [26]:
arr.shape

(2, 2, 2)

Temos um "cubo" de informações, então a localização agora deve ser tridimensional:

In [27]:
arr[0,0,1]

2

In [28]:
arr[1,1,0]

7

Vamos agora ver como filtrar (ou fatiar) um array:

In [29]:
# o comando arange criar um array unidimensional com o tamanho especficado
data = np.arange(10)
data

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [30]:
data[0:5]

array([0, 1, 2, 3, 4])

Alterando os elementos de um array:

In [31]:
data[0:5] = -99
data

array([-99, -99, -99, -99, -99,   5,   6,   7,   8,   9])

Criando subgrupo do array:

In [32]:
data_1 = data[0:5]
data_1

array([-99, -99, -99, -99, -99])

In [33]:
data_1[2:4] = 5555
data

array([ -99,  -99, 5555, 5555,  -99,    5,    6,    7,    8,    9])

Realizando o fatiamento dos dados do array:

In [34]:
data_c = data[5:].copy()
data_c

array([5, 6, 7, 8, 9])

In [35]:
data_c[0:3] = -99
data_c

array([-99, -99, -99,   8,   9])

In [36]:
# array original
data

array([ -99,  -99, 5555, 5555,  -99,    5,    6,    7,    8,    9])

Fatiamento condicional:

In [37]:
data = np.arange(10)
data[data > 5]

array([6, 7, 8, 9])

Listar elementos cujo valor é igual a 4

In [38]:
data[data == 4]

array([4])

Listar elementos cujo valor é diferente de 4

In [39]:
data[data != 4]

array([0, 1, 2, 3, 5, 6, 7, 8, 9])

Listar elementos cujo valor é maior que 4

In [40]:
data[data > 4]

array([5, 6, 7, 8, 9])